import { useState, useEffect } from "react";
import { View, ScrollView } from "react-native";
import { useLocalSearchParams } from "expo-router";
import { useTheme, spacing, radius } from "@/src/theme";
import { AppText, Icon, Card, Loading, EmptyState } from "@/src/ui";
import { StackHeader } from "@/src/Header";
import { api } from "@/src/api";

export default function CreationView() {
  const { colors } = useTheme();
  const { id } = useLocalSearchParams<{ id: string }>();
  const [item, setItem] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.get("/ai/creations").then((r) => setItem(r.creations.find((c: any) => c.id === id))).catch(() => {}).finally(() => setLoading(false));
  }, [id]);

  if (loading) return <View style={{ flex: 1, backgroundColor: colors.surface }}><StackHeader title="Loading…" /><Loading /></View>;
  if (!item) return <View style={{ flex: 1, backgroundColor: colors.surface }}><StackHeader title="Not found" /><EmptyState icon="alert-circle-outline" title="Creation not found" /></View>;

  const c = item.content || {};

  return (
    <View style={{ flex: 1, backgroundColor: colors.surface }}>
      <StackHeader title={item.title} subtitle={item.kind} />
      <ScrollView contentContainerStyle={{ padding: spacing.lg }}>
        {item.kind === "presentation" && c.slides ? (
          <View style={{ gap: spacing.md }}>
            {c.title ? <AppText size="xxl" weight="heavy" style={{ marginBottom: spacing.sm }}>{c.title}</AppText> : null}
            {c.slides.map((s: any, i: number) => (
              <Card key={i}>
                <View style={{ flexDirection: "row", alignItems: "center", marginBottom: spacing.sm }}>
                  <View style={{ width: 26, height: 26, borderRadius: 8, backgroundColor: colors.brandTertiary, alignItems: "center", justifyContent: "center", marginRight: 8 }}>
                    <AppText size="sm" weight="bold" color={colors.brandPrimary}>{i + 1}</AppText>
                  </View>
                  <AppText weight="bold" size="lg" style={{ flex: 1 }}>{s.heading}</AppText>
                </View>
                {(s.bullets || []).map((b: string, j: number) => (
                  <View key={j} style={{ flexDirection: "row", marginBottom: 4 }}>
                    <AppText color={colors.brandPrimary}>•  </AppText>
                    <AppText style={{ flex: 1 }}>{b}</AppText>
                  </View>
                ))}
                {s.notes ? <AppText size="sm" muted style={{ marginTop: spacing.sm, fontStyle: "italic" }}>Notes: {s.notes}</AppText> : null}
              </Card>
            ))}
          </View>
        ) : item.kind === "spreadsheet" && c.columns ? (
          <Card>
            <ScrollView horizontal showsHorizontalScrollIndicator={false}>
              <View>
                <View style={{ flexDirection: "row", borderBottomWidth: 2, borderBottomColor: colors.border, paddingBottom: 8 }}>
                  {c.columns.map((col: string, i: number) => (
                    <View key={i} style={{ width: 130, paddingHorizontal: 6 }}><AppText weight="bold" size="sm">{col}</AppText></View>
                  ))}
                </View>
                {(c.rows || []).map((row: any[], ri: number) => (
                  <View key={ri} style={{ flexDirection: "row", paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: colors.divider }}>
                    {row.map((cell, ci) => (
                      <View key={ci} style={{ width: 130, paddingHorizontal: 6 }}><AppText size="base">{String(cell)}</AppText></View>
                    ))}
                  </View>
                ))}
              </View>
            </ScrollView>
            {c.summary ? <AppText muted style={{ marginTop: spacing.md }}>{c.summary}</AppText> : null}
          </Card>
        ) : (
          <Card>
            <AppText size="md" style={{ lineHeight: 23 }}>{c.markdown || item.prompt}</AppText>
          </Card>
        )}
        <View style={{ flexDirection: "row", alignItems: "center", marginTop: spacing.lg, padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.brandTertiary }}>
          <Icon name="sparkles" size={16} color={colors.brandPrimary} />
          <AppText size="sm" color={colors.onBrandTertiary} style={{ flex: 1, marginLeft: 8 }}>Generated by Chatly AI. Export to PPTX/PDF/XLSX activates on a device build.</AppText>
        </View>
      </ScrollView>
    </View>
  );
}
